### ISSUE TITLE
Question: JSONLines support

### ISSUE THREAD

**Issue by tsenart** [sgreben/jp#17]
Thanks for this project. It looks very promising and match made in heaven for integration with [Vegeta](https://github.com/tsenart/vegeta) in ways similar to these: https://github.com/tsenart/vegeta#usage-real-time-analysis

Vegeta can dump results in [JSONLines](http://jsonlines.org/) format and I couldn't figure out if JSONPath supports this.

A current workaround is to use a rather difficult jq expression to convert JSONLines to JSON:
`jq -nr '"[", try (input|tojson, repeat(",\n\(input|tojson)")), "]"'`

**Comment by sgreben** [comment]
Hey, thanks for opening the issue! I'll just add JSONLines support as another alternative to CSV and JSON. Until that's done, you might want to use the simpler `jq -s` to collect JSONLines into an array, e.g.:

```sh
$ echo 1 2 3  '{"a":123}' | jq -s
[
  1,
  2,
  3,
  {
    "a": 123
  }
]
```

**Comment by tsenart** [comment]
@sgreben: Nice!

**Comment by tsenart** [comment]
To be honest, with such a simple `jq` command at hand (`jq -s`),  I don't know if it's worth it to implement it directly in `jp`. I'd just clearly document how to work with JSONLines using that jq command.

**Comment by sgreben** [comment]
@tsenart yeah, that makes sense. I've added a [JSONLines section](https://github.com/sgreben/jp#jsonlines-input) to the README now. 

I am thinking about significantly re-designing the CLI, perhaps that will be a better time to add "native" JSONLines support.  I'd close the issue for now - is that ok with you?

**Comment by tsenart** [comment]
SGTM
