### ISSUE TITLE
Linux 32bit version

### ISSUE THREAD

**Issue by nikolas-n** [sgreben/jp#2]
It there a linux 32bit version that I could use?

Thanks

**Comment by sgreben** [comment]
Sure, I'll make one! One sec.

**Comment by sgreben** [comment]
@nikolas-n Could you give https://github.com/sgreben/jp/releases/download/1.0.0/jp_1.0.0_linux_x86_32.zip a try?

**Comment by nikolas-n** [comment]
It works! Thanks, and sorry for the late reply!
