### ISSUE TITLE
raspbian support

### ISSUE THREAD

**Issue by sgreadly** [sgreben/jp#21]
Hey there,

Was wondering if you'd support raspbian on raspberry pi? I can't seem to `make` successfully. It just auto-cleans without creating binaries. Also the arm64 doesn't work.. 

$ ./jp
-bash: ./jp: cannot execute binary file: Exec format error

jp $ uname -a
Linux t5 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

**Comment by olinorwell** [comment]
To get it running on Raspbian all you need to do is install the Go compiler.

sudo apt-get install golang
go get -u github.com/sgreben/jp/cmd/jp

Then the binary should be at:
~/go/bin/jp

Works well for me

**Comment by sgreadly** [comment]
Thanks! That did the trick.
