### ISSUE TITLE
Sending chart from CLI 

### ISSUE THREAD

**Issue by PavelKa** [sgreben/jp#25]
Hello, I'd like to use Your utility to send a simple chart via mail from a command line in Linux.  But there are an unreadable bunch of chars â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  in the received email, if I pipe result from jp to "mail -s ..." command although jp works perfectly in CLI.  
Do You have any advice on how to send a chart via email from CLI, please?

**Comment by sgreben** [comment]
Hey! I'm pretty sure this is a matter of setting the correct encoding (utf-8, in this case) for the mail - have a look at the answers here: <https://stackoverflow.com/questions/3120168/how-to-send-special-characters-via-mail-from-a-shell-script>, in particular

```sh 
mail -a "Content-Type: text/plain; charset=UTF-8"
```

looks promising :)

**Comment by PavelKa** [comment]
Thank's for Your prompt action, the proposed solution really helps...
