### ISSUE TITLE
arm64 version

### ISSUE THREAD

**Issue by vielmetti** [sgreben/jp#4]
Compiling and running the program on an arm64 machine (Packet Type 2A) works without any issues. If you have the chance to generate a binary for arm64, I'm happy to also give it a quick test.

**Comment by sgreben** [comment]
Cool, thanks for checking! Could you give https://github.com/sgreben/jp/releases/download/1.0.1/jp_1.0.1_linux_arm64.zip a try?

**Comment by vielmetti** [comment]
Works fine - and doesn't core dump with the `echo "" | jp` test.

**Comment by sgreben** [comment]
Great, many thanks for testing it out! I'll close this issue then.
