### ISSUE TITLE
Sub-character resolution

### ISSUE THREAD

**Issue by sgreben** [sgreben/jp#5]
Other libraries - for example, [termui](https://github.com/gizak/termui/blob/master/linechart.go#L13) - use braille symbols (`⣀⡠⡐⡈` etc.) to effectively double the plot resolution. It would be nice if we could do that also (probably by default / simply instead of the current full-block character).

**Comment by sgreben** [comment]
Actually, braille gives us 8 pixels / character if we use it like [UnicodePlots](https://github.com/Evizero/UnicodePlots.jl#low-level-interface). This would also make scatterplots much more useful.

**Comment by AShedko** [comment]
For a more mature package, perhaps one could look into [drawille](https://github.com/asciimoo/drawille)

Although Julia's type system is more similar to Go than Python's

**Comment by sgreben** [comment]
Added braille (2x4) & quarter-block (2x2) canvas in 1.1.0.
